"""empty message

Revision ID: c92937539d59
Revises: c36bafa95145
Create Date: 2023-10-02 13:45:49.626504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92937539d59'
down_revision = 'c36bafa95145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_group_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vyrobek')
    # ### end Alembic commands ###
